management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  contact:
    name: sboot-demo
    email: jybjobs@sina.cn